version: '3'
services:
  db:
    image: "postgres"
    container_name: jobs-db
    env_file:
      - db.env
    ports:
      - "5432:5432"
    volumes:
      - ./migration/0_initial_db.sql:/docker-entrypoint-initdb.d/0_initial_db.sql
      - ./migration/1_user_roles.sql:/docker-entrypoint-initdb.d/1_user_roles.sql
      - ./migration/2_search_vector_trigger.sql:/docker-entrypoint-initdb.d/2_search_vector_trigger.sql
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - jobs-net
    restart: always

  app:
    build: 
      context: ./
      target: prd
    container_name: jobs-be
    depends_on:
      - db
    networks:
      - jobs-net
    env_file:
      - server.env
    volumes:
      - ./src:/app/src
      - ./uploads:/app/uploads
    restart: always
    ports:
      - "8080:8080"
      - "2345:2345"
    security_opt:
      - "seccomp:unconfined"

networks:
  jobs-net:
    driver: bridge
volumes:
  images_volume:
