version: '3'
services:
  db:
    image: "postgres"
    container_name: jobs-db
    env_file:
      - db.env
    ports:
      - "5432:5432"
    volumes:
      - ./migration/1_initial_db.sql:/docker-entrypoint-initdb.d/1_initial_db.sql
      - ./migration/2_user_roles.sql:/docker-entrypoint-initdb.d/2_user_roles.sql
      - ./migration/3_search_vector_trigger.sql:/docker-entrypoint-initdb.d/3_search_vector_trigger.sql
    restart: always