version: '3'
services:
  db:
    image: "postgres"
    container_name: jobs-db
    env_file:
      - db.env
    ports:
      - "5432:5432"
    volumes:
      - ./migration/0_initial_db.sql:/docker-entrypoint-initdb.d/0_initial_db.sql
      - ./migration/1_user_roles.sql:/docker-entrypoint-initdb.d/1_user_roles.sql
      - ./migration/2_search_vector_trigger.sql:/docker-entrypoint-initdb.d/2_search_vector_trigger.sql
    restart: always