version: '3'
services:
  db:
    image: "postgres"
    container_name: jobs-db
    env_file:
      - db.env
    ports:
      - "5432:5432"
    volumes:
      - ./migration/000001_initial_db.up.sql:/docker-entrypoint-initdb.d/000001_initial_db.up.sql
      - ./migration/000002_user_roles.up.sql:/docker-entrypoint-initdb.d/000002_user_roles.up.sql
      - ./migration/000003_search_vector_trigger.up.sql:/docker-entrypoint-initdb.d/000003_search_vector_trigger.up.sql
    restart: always