name: Go

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  int-tests:
    runs-on: ubuntu-latest
    env:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: jobsfinder
      DB_PORT: 5432
      PORT: 8080

    services:
      postgres:
        image: postgres:latest
        env: 
          POSTGRES_USER: root
          POSTGRES_PASSWORD: root
          POSTGRES_DB: jobsfinder
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U testuser"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    
    steps:    
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'
    - name: Run database migration
      run: |
        go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latest
        migrate -database "postgres://testuser:testpassword@localhost:5432/testdb?sslmode=disable" -path ./migrations up
    - name: Test
      run: go test -v ./src/...
    

  build:
    needs: int-tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build
      run: go build -v ./...
