name: Go

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  int-tests:
    runs-on: ubuntu-latest
    env:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: jobsfinder
      DB_PORT: 5432
      PORT: 8080

    services:
      postgres:
        image: postgres:latest
        env: 
          POSTGRES_USER: root
          POSTGRES_PASSWORD: root
          POSTGRES_DB: jobsfinder
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U testuser"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    
    steps:    
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'
    
    - name: Install golang-migrate
      run: |
        curl --output install.sh https://raw.githubusercontent.com/pressly/goose/master/install.sh
        sudo GOOSE_INSTALL=/usr sh install.sh
        which goose

    - name: Up migrations
      run: goose -allow-missing -dir=./migrations postgres postgres://root:root@localhost:5432/jobsfinder?sslmode=disable up

    - name: Down migrations
      run: goose -allow-missing -dir=./migrations postgres postgres://root:root@localhost:5432/jobsfinder?sslmode=disable down
    
    
    - name: Test
      run: go test -v ./src/...
    

  build:
    needs: int-tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build
      run: go build -v ./...
